spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: "!@#1133Uzumymu7+++"
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/prod
    baseline-on-migrate: true
    validate-on-migrate: true

  mail:
    host: ${MAIL_HOST_PROD}
    port: ${MAIL_PORT_PROD}
    username: ${MAIL_USERNAME_PROD}
    password: ${MAIL_PASSWORD_PROD}

  jwt:
    secret: ${JWT_SECRET_PROD}
    expiration: ${JWT_EXPIRATION_PROD}

  server:
    port: ${SERVER_PORT_PROD}

ratelimit:
  login:
    maxAttemptsPerIp: ${RATE_LIMIT_LOGIN_MAX_ATTEMPTS_PER_IP:15}
    maxAttemptsPerEmail: ${RATE_LIMIT_LOGIN_MAX_ATTEMPTS_PER_EMAIL:10}
    ttlSeconds: ${RATE_LIMIT_LOGIN_TTL_SECONDS:60}

  refresh:
    maxAttemptsPerIp: ${RATE_LIMIT_REFRESH_MAX_ATTEMPTS_PER_IP:30}
    ttlSeconds: ${RATE_LIMIT_REFRESH_TTL_SECONDS:60}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3002,http://localhost:3300, http://appgestaotibp-devcontainer.local:8088}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  exposed-headers: ${CORS_EXPOSED_HEADERS:Set-Cookie}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

auth:
  cookies-durations:
    access-token-min: ${AUTH_ACCESS_TOKEN_DURATION_MIN}
    refresh-short-min: ${AUTH_REFRESH_TOKEN_SHORT_MIN}
    refresh-long-min: ${AUTH_REFRESH_TOKEN_LONG_MIN}
    twofa-short-min: ${AUTH_TWOFA_TOKEN_SHORT_MIN}

  cookies-properties:
    secure: ${AUTH_COOKIE_SECURE}
    http-only: ${AUTH_COOKIE_HTTP_ONLY}
    same-site: ${AUTH_COOKIE_SAMESITE}

  cookie-names:
    access: ${AUTH_COOKIE_NAME_ACCESS}
    refresh: ${AUTH_COOKIE_NAME_REFRESH}
    twofa: ${AUTH_COOKIE_NAME_2FA}

auth-paths:
  public-paths:
    - /api/auth/login
    - /api/auth/register
    - /api/auth/2fa/validate-login
    - /api/auth/validate
    - /api/auth/session
    - /api/auth/refresh
    - /api/auth/DevTest
    - /api/health
    - /api/auth/logout
    - /swagger-ui/*
    - /v3/api-docs
