spring:
  config:
    activate:
      on-profile: dev-local

  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/dev
    baseline-on-migrate: true
    validate-on-migrate: true

  mail:
    host: ${MAIL_HOST_DEV}
    port: ${MAIL_PORT_DEV}
    username: ${MAIL_USERNAME_DEV}
    password: ${MAIL_PASSWORD_DEV}

  jwt:
    secret: ${JWT_SECRET_DEV}
    expiration: ${JWT_EXPIRATION_DEV}

  server:
    port: ${SERVER_PORT_DEV}

ratelimit:
  login:
    maxAttemptsPerIp: ${RATE_LIMIT_LOGIN_MAX_ATTEMPTS_PER_IP:10}
    maxAttemptsPerEmail: ${RATE_LIMIT_LOGIN_MAX_ATTEMPTS_PER_EMAIL:5}
    ttlSeconds: ${RATE_LIMIT_LOGIN_TTL_SECONDS:60}

  refresh:
    maxAttemptsPerIp: ${RATE_LIMIT_REFRESH_MAX_ATTEMPTS_PER_IP:20}
    ttlSeconds: ${RATE_LIMIT_REFRESH_TTL_SECONDS:60}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3002,http://localhost:3300, http://appgestaotibp-devcontainer.local:8088}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}

auth:
  cookies-durations:
    access-token-min: ${AUTH_ACCESS_TOKEN_DURATION_MIN}
    refresh-short-min: ${AUTH_REFRESH_TOKEN_SHORT_MIN}
    refresh-long-min: ${AUTH_REFRESH_TOKEN_LONG_MIN}
    twofa-short-min: ${AUTH_TWOFA_TOKEN_SHORT_MIN}

  cookies-properties:
    secure: ${AUTH_COOKIE_SECURE}
    http-only: ${AUTH_COOKIE_HTTP_ONLY}
    same-site: ${AUTH_COOKIE_SAMESITE}

  cookie-names:
    access: ${AUTH_COOKIE_NAME_ACCESS}
    refresh: ${AUTH_COOKIE_NAME_REFRESH}
    twofa: ${AUTH_COOKIE_NAME_2FA}

auth-paths:
  public-paths:
    - /api/auth/login
    - /api/auth/register
    - /api/auth/2fa/validate-login
    - /api/auth/validate
    - /api/auth/session
    - /api/auth/refresh
    - /api/auth/DevTest
    - /api/health
    - /api/auth/logout
    - /swagger-ui/*
    - /v3/api-docs
