- name: Login no GitHub Container Registry
  uses: docker/login-action@v2
  with:
    registry: ghcr.io
    username: devrafaelrabelo
    password: ${{ secrets.GHCR_PAT }}

- on:
    push:
      branches: ["main"]

- jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout código
          uses: actions/checkout@v3

        - name: Login no GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build e push da imagem Docker
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile.prod
            push: true
            tags: ghcr.io/devrafaelrabelo/appgestaoti-controlcenter:latest
